// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
)

type User struct {
	ID               int64        `json:"id"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
	TotalLinks       int32        `json:"total_links"`
	Credit           int32        `json:"credit"`
	LastCreditUpdate sql.NullTime `json:"last_credit_update"`
	IsBanned         bool         `json:"is_banned"`
	IsDeleted        bool         `json:"is_deleted"`
	IsVerified       bool         `json:"is_verified"`
	IsPremium        bool         `json:"is_premium"`
}
